# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67621f49acb60fdf0dd9fd5dc7655319a73dcbdb0927220edae3e106aee93efbf56e378dc850ff0cb97affa8d2a663966c2064cb74e9f05d4d7187e1444ba0b8

test:
  secret_key_base: 7a652b93e0145def717ab1fa0aa7f0f3aad3c15191374ae95cf4c8fdfcfb756dc7807deeb0c3ecf2abcca3ead75137c5872458d94a10579b8ef116345c68d330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
